package models

type ReferenceData struct {
	Sites       []Site       `json:"sites"`
	Modalities  []Modality   `json:"modalities"`
	BodyParts   []BodyPart   `json:"body_parts"`
	Credentials []Credential `json:"credentials"`
}

type Site struct {
	Code string `json:"code"`
	Name string `json:"name"`
}

type Modality struct {
	Code string `json:"code"`
	Name string `json:"name"`
}

type BodyPart struct {
	Name         string `json:"name"`
	SearchString string `json:"search_string"`
}

var DefaultBodyPart = []*BodyPart{
	{Name: "ABDOMEN", SearchString: "AABDMN, AABDOMEN, ABD, ABDM, ABDMN, ABDO, ABDOEM, ABDOEMN, ABDOEN, ABDOI, ABDOKEN, ABDOM, ABDOME, ABDOMEB, ABDOMEM, ABDOMEN, ABDOMENAL, ABDOMENM, ABDOMENROUTINE, ABDOMENRP, ABDOMENT, ABDOMIN, ABDOMINAL, ABDOMN, ABDOMNE, ABDOMNEN, ABDOMRN, ABDOMWN, ABDONMEN, ABDOO, ABDOP"},
	{Name: "ADRENALS", SearchString: "ADRENAL, ADRENALS"},
	{Name: "ANKLE", SearchString: "ANK, ANKE, ANKEL, ANKKLE, ANKL, ANKLE, ANKLEL, ANKLES, ANKLL, ANKLR, ANLE, ERANKLE, LTANKLE, RANKLE, RIGHTANKLE, RTANKLE"},
	{Name: "APPENDIX", SearchString: "APPENDIX"},
	{Name: "ARMS", SearchString: "ARM, ARMS"},
	{Name: "BACK", SearchString: "BA, BACK"},
	{Name: "BLADDER", SearchString: "BLADDER, CYSTO, CYSTOGRAM"},
	{Name: "BOWEL", SearchString: "BOWEL"},
	{Name: "BRAIN", SearchString: "BRAI, BRAIHN, BRAIJ, BRAIMN, BRAIN, BRAINAND, BRAINC, BRAINHR, BRAINM, BRAINNC, BRAINS, BRAINSTEM, BRAINWC, BRAION, BRAN, CEREBRAL, NEURO"},
	{Name: "BREAST", SearchString: "BREAST, BREASTA, BREASTS, BREAT, BREST, MAMMO, MAMMOGRAM, MAMMOGRAPHY, SCREENING"},
	{Name: "BUTTOCK", SearchString: "BUTTOCK"},
	{Name: "CALF", SearchString: "CALF"},
	{Name: "CAROTID", SearchString: "CARORIDS, CAROT, CAROTD, CAROTDS, CAROTID, CAROTIDAT, CAROTIDE, CAROTIDS, CAROTIDSAT, CAROYID, CTCAROTID, DUSCAROTID"},
	{Name: "CHEST", SearchString: "CHE, CHEAST, CHEAT, CHES, CHESST, CHEST, CHESTM, CHESTN, CHESTS, CTCHEST"},
	{Name: "CLAVICLE", SearchString: "CLAV, CLAVICAL, CLAVICLE, CLAVICLES, CLAVICULAR, CLAVIVLE, CLAVR"},
	{Name: "COLON", SearchString: "CCOLON, COLO, COLON, COLONOGRAPHY, COLONS, COLOP"},
	{Name: "CSPINE", SearchString: "CERV, CERVICAL, CERVICLA, CERVIX, CEVICAL, CSPINE, OPCERVICAL, RSPCCERVICAL"},
	{Name: "DENTAL", SearchString: "DENTAL, OPG, PANORAMA, PANOREX"},
	{Name: "DUODENUM", SearchString: "DUO, DUOD, DUODENAL, DUODENUM"},
	{Name: "EARS", SearchString: "EAR, EARS"},
	{Name: "ELBOWS", SearchString: "ELB, ELBOW, ELBOWE, ELBOWS, ELBWL, ELBWR"},
	{Name: "ESOPHAGUS", SearchString: "ESOPHAGUS, ESOPHGUS, ESOPHOGUS"},
	{Name: "EYES", SearchString: "EYE, EYES"},
	{Name: "FACE", SearchString: "FAC, FACE, FACIAL"},
	{Name: "FEET", SearchString: "FEED, FEET, FEETX, FOOT, FOOTL, FOOTR, LFEET, LFOOT, LFT, LTFOOT, MIDFOOT, OPFOOT, RFEET, RFOOT, RFT"},
	{Name: "FEMURS", SearchString: "FEMUR, FEMURS"},
	{Name: "FINGERS", SearchString: "FINGER, FINGERS"},
	{Name: "FOREARMS", SearchString: "FOREARM, FOREARMS"},
	{Name: "GROIN", SearchString: "GROIN"},
	{Name: "HANDS", SearchString: "DXHAND, HAND, HANDL, HANDLED, HANDR, HANDS"},
	{Name: "HEAD", SearchString: "CDCTHEAD, CTHEAD, HEAD, HEAD1, HEAD2, HEADC, HEADNC, HEADROUTINE, HEADS, HEADSEQ, HEADSTEREO, HEADTC, HEADTRAUMA, HEADWC, HEADWITH, HEAED, HEAF, HEAFD, MANDIBLE, TEMPLE"},
	{Name: "HEART", SearchString: "CARDIAC, CORONARY, ECHOCARDIOGRAM, HEART, MYOCARDIAL"},
	{Name: "HEELS", SearchString: "HEEL, HEELS"},
	{Name: "HIP", SearchString: "DXHIP, HIP, HIPCT, HIPL, HIPNAIL, HIPNL, HIPNLL, HIPNR, HIPPING, HIPR, HIPS"},
	{Name: "HUMERUS", SearchString: "HUM, HUME, HUMERI, HUMERII, HUMEROUS, HUMERUS"},
	{Name: "KIDNEYS", SearchString: "CDULRENAL, KID, KIDNEY, KIDNEYS, REN, RENAL, RENALAT, RENALBX, RENALCT, RENALD, RENALL, RENALS"},
	{Name: "KNEES", SearchString: "CDKNEE, DXKNEE, KNEE, KNEEHR, KNEEL, KNEER, KNEES, KNEES BOTH, KNES"},
	{Name: "KUB", SearchString: "CDKUB, CRKUB, CTKUB, CYKUB, IVP, KUB, KUD, KUIB, KUN, PYELOGRAM, TCKUB, UROGRAM"},
	{Name: "LEGS", SearchString: "GDCLEG, LEG, LEGFS, LEGS, LEGSC, LEGV"},
	{Name: "LIVER", SearchString: "LIVER, LIVERBX, LIVERC, LIVERCT"},
	{Name: "LOWEREXTREMITY", SearchString: "LOWEREXTREMITIES, LOWEREXTREMITY, LOWEXM"},
	{Name: "LSPINE", SearchString: "ANDLUMB, ANDLUMBAR, ERLUMBAR, LSPINE, LSPINENC, LSPINEP, LSPINEPR, LSPINEPRO, LSPINEPROB, LSPINEPROBE, LSPINEPROBEM, LSPINEPROBEMS, LSPINEPROBEMSL, LSPINEPROBEMSLT, LSPINEPROBEMSLTR, LSPINEPROBEMSLTRP, LSPINEPROBEMSLTRPR, LSPINEPROBEMSLTRPRT, LSPINEPROBEMSLTRPRTL, LSPINEPROBEMSLTRPRTLT, LSPINEPROBEMSLTRPRTLTR, LSPINEPROBEMSLTRPRTLTRP, LSPINEPROBEMSLTRPRTLTRPR, LSPINEPROBEMSLTRPRTLTRPRT, LSPINEPROBEMSLTRPRTLTRPRTL, LSPINEPROBEMSLTRPRTLTRPRTLT, LSPINEPROBEMSLTRPRTLTRPRTLTR, LSPINEPROBEMSLTRPRTLTRPRTLTRP, LSPINEPROBEMSLTRPRTLTRPRTLTRPR, LSPINEPROBEMSLTRPRTLTRPRTLTRPRT, LSPINEPROBEMSLTRPRTLTRPRTLTRPRTL, LSPINEPROBEMSLTRPRTLTRPRTLTRPRTLT, LSPINEPROBEM"},
	{Name: "LUNG", SearchString: "LUNG, PULMONARY, PV"},
	{Name: "NECK", SearchString: "CAPNECK, CTNECK, NEC, NECK, NECKC, NECKROUTINE, NECKWC, STNECK"},
	{Name: "NOSE", SearchString: "NASAL, NOSE"},
	{Name: "OBSTETRIC", SearchString: "FETAL, OB, OBSTEREICAL, OBSTERTICAL, OBSTETRIC, OBSTETRICAL, OBSTETRICS, PREGNANCY"},
	{Name: "ORBITS", SearchString: "ORBIT, ORBITS"},
	{Name: "OVARIES", SearchString: "OVARIAN, OVARIES, OVARY"},
	{Name: "PANCREAS", SearchString: "PAN, PANC, PANCREAS"},
	{Name: "PAROTID", SearchString: "PAROTID"},
	{Name: "PATELLA", SearchString: "KNEECAP, PATELL, PATELLA, PATELLAE, PATELLAR, PATELLAS, PATELLAX, PATELLS"},
	{Name: "PELVIS", SearchString: "CDPELVIS, CDULPELVIS, CTPELVIS, DPELVIS, GDCPELVIS, HEMIPELVIS, OPELVIS, OPPELVIS, PEL, PELC, PELV, PELVC, PELVI, PELVIC, PELVIS, PELVISAND, PELVISBX, PELVISROUTINE, PELVISST, PELVISWC, PELVIV, PELVIX, PELVLIS, PELVOS, PELVS, PELVSI, PELVWC, PELWC, PELXR, PEV, PEVIS, PEVLIS, PLEVIS"},
	{Name: "PITUARYGLAND", SearchString: "PITUARY, PITUARYGLAND, PITUITARY"},
	{Name: "PROSTATE", SearchString: "PROSTATE"},
	{Name: "RECTUM", SearchString: "RECTUM"},
	{Name: "RIBS", SearchString: "RIB, RIBB, RIBBS, RIBS, RIBS1"},
	{Name: "SACRUM", SearchString: "SACRUM"},
	{Name: "SCAPHOID", SearchString: "SCAPH, SCAPHIOD, SCAPHO, SCAPHOID, SCAPHOIDS, SCAPHOIE, SCAPOID"},
	{Name: "SCAPULA", SearchString: "SCAPULA"},
	{Name: "SCROTUM", SearchString: "SCROTUM"},
	{Name: "SHOULDERS", SearchString: "LDSHOULDER, MRISHOULDER, SH, SHLD, SHLDR, SHOL, SHOUL, SHOULD, SHOULDER, SHOULDERS, SHOULDR, SHOULDRES, SHOULDS, SHOULER, SHOULL, SHOULRT, SHOULS, SHOUOLDER, SHOUR, SHOUULDER"},
	{Name: "SINUSES", SearchString: "SINSES, SINSU, SINSUEES, SINSUES, SINSUSES, SINUA, SINUES, SINUS, SINUSDES, SINUSE, SINUSES, SINUSESC, SINUSORBI, SINUSSTEALTH, SISNUSES"},
	{Name: "SKULL", SearchString: "SKULL"},
	{Name: "SPINE", SearchString: "SPINE"},
	{Name: "STOMACH", SearchString: "STOM, STOMA, STOMACH"},
	{Name: "TESTES", SearchString: "TESTES, TESTI, TESTIC, TESTICLE, TESTICLES, TESTICULAR"},
	{Name: "THIGH", SearchString: "THIGH, THIGHS"},
	{Name: "THORAX", SearchString: "THORAX, THORAXBKW, THORAXC, THORAXHI, THORAXROUTINE"},
	{Name: "THUMBS", SearchString: "THUMB, THUMBS"},
	{Name: "THYROID", SearchString: "THY, THYR, THYRD, THYRIOD, THYROI, THYROID, THYROIDAT, THYROYD"},
	{Name: "TIBIAFIBULA", SearchString: "FIB, FIBULA, TIB, TIBFIB, TIBIA, TIBIAFIBULA, TIBIAL, TIBIAS"},
	{Name: "TOES", SearchString: "TOE, TOES"},
	{Name: "TONGUE", SearchString: "TONGUE"},
	{Name: "TORSO", SearchString: "TORSO"},
	{Name: "TRANSVAG", SearchString: "ENDOVAG, ENDOVAGINAL, GYN, TRANSVAG, TRANSVAGINAL"},
	{Name: "TSPINE", SearchString: "THORACIC, THORAIC, THORASI, THORASIC, TSPINE"},
	{Name: "UPPEREXTREMITY", SearchString: "UPEXM, UPPEREXTREMITIES, UPPEREXTREMITY"},
	{Name: "URETER", SearchString: "URETER, URETERS"},
	{Name: "WRISTS", SearchString: "CDWRIST, LTWRIST, LWRIST, RTWRIST, WRIST, WRISTNC, WRISTS, WRISTUHR"},
}

type Attribute struct {
	Code string `json:"code"`
	Name string `json:"name"`
}

var DefaultAttributes = []*Attribute{
	{Code: "ADULT", Name: "ADULT, MIADULT, WCADULT"},
	{Code: "ANEURYSM", Name: "ANEUR, ANEURYSM, ANEURYSMAL, ANEURYSMS, ANEYRYSM"},
	{Code: "ANGIO", Name: "ANGIO, ANGIOGRAM"},
	{Code: "AP", Name: "AP, PA"},
	{Code: "ARTERIOGRAM", Name: "ARTERIOGRAM"},
	{Code: "ARTHROGRAM", Name: "ARTHRO, ARTHROGRAM"},
	{Code: "BILATERAL", Name: "BI, BIL, BILAT, BILATERAL"},
	{Code: "BIOPSY", Name: "BIOP, BIOPS, BIOPSY, BIOPSYLEFT, BIOPSYRIGHT, BIOS, BIOSPY, BIOSY"},
	{Code: "BLEEDING", Name: "BLEED, BLEEDING"},
	{Code: "BLOCK", Name: "BLOCK"},
	{Code: "BONE", Name: "BONE"},
	{Code: "CASCORE", Name: "CASCORE, SCORE"},
	{Code: "CATHETER", Name: "CATH, CATHETER"},
	{Code: "COMPLETE", Name: "COMPLETE"},
	{Code: "DIAGNOSTIC", Name: "DIAG, DIAGNOSTIC"},
	{Code: "DOPPLER", Name: "DOPPLER"},
	{Code: "DRAIN", Name: "DRAIN, DRAINAGE"},
	{Code: "DUPLEX", Name: "DUPLEX"},
	{Code: "FISTULA", Name: "FISTULA"},
	{Code: "FRACTURE", Name: "FRACTURE"},
	{Code: "JOINT", Name: "JNT, JNTS, JOINT, JOINTS, JOPINTS"},
}

type Credential struct {
	Code string `json:"code"`
	Name string `json:"name"`
}

var DefaultCredentials = []*Credential{
	{Code: "FR", Name: "FR"},
	{Code: "FRAC", Name: "FRAC"},
	{Code: "FRCR", Name: "FRCR"},
	{Code: "FRCR(R)", Name: "FRCR(R)"},
}
